Repository freezingsaddles/freezing-sync, pull requests merged in 2025-02, with the labels that each got.

#92 Don't fetch photos from private rides
  freezing/sync/data/activity.py
Labels: enhancement

#100 Fix a variety of sync issues
  freezing/sync/data/activity.py
  freezing/sync/data/streams.py
  freezing/sync/utils/cache.py
Labels: bug

#102 Trivial spacing fix
  README.md
Labels: enhancement, documentation
